spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/?user=root?serverTimezone=Asia/Seoul
    username: root
    password: batch
logging:
  level:
    root: info
    com.test.batch: debug
